.Dd $Mdocdate: December 18 2022 $
.Dt FNAIFY 1
.Os
.Sh NAME
.Nm fnaify
.Nd run FNA/XNA games on OpenBSD
.Sh SYNOPSIS
.Nm
.Op Fl i | y
.Op Fl hnsv
.Op Fl c Ar configfile
.Op Fl D Ar depdir
.Op Fl d Ar gamedir
.Op Fl f Ar frameworkfile | Fl F Ar frameworkversion
.Op Fl m Ar monopath
.Op Ar userflags
.Sh DESCRIPTION
.Nm
runs games based on the FNA engine with OpenBSD-native
libraries and its
.Xr mono 1
runtime.
.Pp
As of version 2.0,
.Nm
has been extended to attempt configuring XNA games as well.
.Nm
can be run in 3 basic modes regarding the addition of missing libraries:
restrictive
.Po
default
.Pc
, interactive, and permissive.
.Pp
As of version 3.0,
.Nm
unifies both setup and launch of supported games in one command.
.Pp
All games require additional libraries from ports, like SDL2. Some of
them can be found in the fnaify-extralibs package, like libatomstb or
libfmod_SDL.
.Pp
The arguments are as follows:
.Bl -tag -width Ds
.It Fl i | y
The mode determines how
.Nm
handles situations where compatibility problems are identified that can
be addressed with drop-in DLL replacements, or where an option needs to
be selected.
With
.Fl i ,
.Nm
runs in interactive mode, meaning the user will be prompted in every
case.
With
.Fl y ,
.Nm
runs in permissive mode
.Po
.Fl y
for
.Dq yes
to all
.Pc .
This means that any suggested drop-in DLLs will be installed,
and if different options are possible (like picking among several .exe
files for the launch script), the first one will be selected
automatically.
If neither
.Fl i
nor
.Fl y
is specified,
.Nm
runs in restrictive mode, that is no drop-in DLLs will be installed.
.It Fl c Ar configfile
Optional. Use
.Ar configfile
for the configuration of
.Xr mono 1 .
This sets up dllmap/dllentry settings to use the correct libraries. See
.Xr mono-config 5
for details. If this option is omitted, 
.Nm
looks first for
.Pa ~/.config/fnaify/fnaify.dllmap.config
and then for
.Pa /usr/local/share/fnaify/fnaify.dllmap.config .
If neither one is found,
.Nm
creates
.Pa ~/.config/fnaify/fnaify.dllmap.config
with default settings.
.It Fl D Ar depdir
Add
.Ar depdir
to the directories to search for native library dependencies.
A directory specified this way will be searched
.Em before
the default locations
.Pq Pa /usr/local/lib No etc. .
.It Fl d Ar gamedir
Path to the game's directory
.Pq defaults to the current working directory .
.It Fl F Ar frameworkversion
Choose a specific framework version to use.
.It Fl f Ar frameworkfile
Framework file to use. Typically
.Pa FNA.dll
or
.Pa MonoGame.Framework.dll .
By default will automatically identify the bundled file in the
game's directory.
.It Fl h
Prints help text.
.It Fl m Ar monopath
Add
.Ar monopath
to the directories the
.Xr mono 1
runtime will search for DLLs.
.It Fl n
Skip checks for library dependencies.
.It Fl s
Force (re-)running setup.
.It Fl V
Display version of
.Nm .
.It Fl v
Verbose mode.
.It Ar userflags
Optional.
Flags that are passed to the game as arguments
.El
.Sh SUPPORTED GAMES
Games marked with [!] may have errors or other significant limitations.
.Pp
.Bl -item -compact
.It
The Adventures of Shuggy
.It
Akane the Kunoichi
.It
Amazing Princess Sarah [!]
.It
Apotheon
.It
Apple Jack 1&2
.It
Atom Zombie Smasher
.It
A Virus Named TOM [!]
.It
Before the Echo [!]
.It
Bird Assassin
.It
Bleed
.It
Bleed 2
.It
Blossom Tales II: The Minotaur Prince
.It
Breath of Death VII
.It
Brushwood Buddies
.It
Camera Obscura
.It
Capsized
.It
Capsule Force
.It
Celeste (no audio)
.It
Chaos Heart [!]
.It
Charlie Murder
.It
Chasm
.It
CometStriker
.It
Cryptark
.It
Crystal Project
.It
Cthulhu Saves the World
.It
Curse of the Crescent Isle DX
.It
Dad Quest
.It
Dead Pixels [!]
.It
Dead Pixels II (Early Access)
.It
Diehard Dungeon
.It
The Dishwasher: Vampire Smile
.It
Draw a Stickman: EPIC
.It
Dust: An Elysian Tail
.It
DwarfCorp
.It
Eagle Island [!]
.It
Eliza
.It
Escape Goat
.It
Escape Goat 2
.It
EXAPUNKS
.It
FEZ [!]
.It
Fist Puncher
.It
Flinthook
.It
Flotilla
.It
Gateways
.It
Glitchangels
.It
Grand Class Melee 2 [!]
.It
Growing Pains
.It
HackNet
.It
Hidden in Plain Sight
.It
Hive
.It
Hyphen
.It
Jon Shafer's At the Gates
.It
LaserCat
.It
Last Call BBS
.It
Little Racers STREET
.It
Mercenary Kings
.It
Miasma: Citizens of Free Thought
.It
Miasma 2: Freedom Uprising [!]
.It
MidBoss
.It
Mobius Front '83 [!]
.It
Molek-Syntez
.It
Mount Your Friends
.It
NeuroVoider [!]
.It
Ninja Warrior
.It
One Finger Death Punch
.It
Opus Magnum
.It
Overdriven Reloaded
.It
Owlboy
.It
Paladin
.It
Penny Arcade's On the Rain-Slick Precipice of Darkness 3
.It
Penny Arcade's On the Rain-Slick Precipice of Darkness 4
.It
Phoenix Force [!]
.It
PlanetFriend
.It
Press X to Not Die
.It
Rex Rocket
.It
Rogue Legacy
.It
Ruggnar
.It
Salt and Sanctuary
.It
Session Seven
.It
Shenzhen I/O
.It
Shipwreck [!]
.It
Signs of Life
.It
Skulls of the Shogun
.It
Soulcaster 1 & 2
.It
SpaceChem
.It
SpeedRunners
.It
Stardew Valley [!]
.It
Steel Assault
.It
Sumico
.It
Super Amazing Wagon Adventure
.It
Super Bernie World
.It
Super Blood Hockey
.It
Super Rad Raygun
.It
Sword of the Stars: The Pit [!]
.It
Terraria
.It
Timespinner
.It
TowerFall: Ascension
.It
Ultra Hat Dimension
.It
Unexplored
.It
Unholy Heights
.It
The Useful Dead
.It
Weapon of Choice [!]
.It
Wizorb [!]
.It
Wyv and Keep
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa /usr/local/share/fnaify/fnaify.dllmap.config
Default configuration file to map DLLs to native libraries.
.It Pa ~/.config/fnaify/fnaify.dllmap.config
User directory configuration file. Takes precedence if it exists.
Make sure to keep it up-to-date!
.El
.Sh EXIT STATUS
.Nm
returns 1 if an error occurred, otherwise 0.
.Sh EXAMPLES
Run in permissive mode, suitable to set up most supported games
automatically.
.Pp
.Dl $ fnaify -y -d path/to/game/directory
.Pp
Run in interactive mode.
.Nm
will prompt the user if any additional DLLs are recommended, or if a
file needs to be selected for the launch script.
.Pp
.Dl $ fnaify -i
.Sh SEE ALSO
.Xr mono 1 ,
.Xr mono-config 5
.Sh HISTORY
The
.Nm
utility was originally created in December 2017 by
.An Thomas Frohwein Aq Mt thfr@openbsd.org .
.Sh RELEASE HISTORY
.Bl -tag -width Ds
.It 3.1
Stop removing Steamworks.NET.dll. Instead, rely on other lower level
native libraries (CSteamworks, libsteam_api). Add flag
.Fl n
to skip library checks.
.It 3.0
Stop creating launch script. Instead use fnaify for both
setup and launch.
Support for several Zachtronics games. Add libstubborn use to dllmap.
Symlinking for MonoGame, e.g. NeuroVoider.
Preferential use of installed FNA.dll over bundled one.
.It 2.2
Fix config for mono 6. Add support for libcestub.
.It 2.1
Support for additional XNA games. Add MONO_FORCE_COMPAT quirk.
.It 2.0
Add support for XNA games.
Introduce interactivity flags
.Fl i | y
to facilitate adding in needed assemblies/libraries.
.It 1.3
Add prompt to download and replace
.Pa FNA.dll
if incompatible version is found.
Detect steamstubs directory and use Steamworks stubs if present.
.It 1.2
FreeBSD portability fixes, account for more special cases (MidBoss,
Adventures of Shuggy, Atom Zombie Smasher), add directory path to plug
in additional libraries.
.It 1.1
Fix bug selecting .exe by separating input variables.
.It 1.0
Initial release.
.El
.Sh AUTHORS
.An -nosplit
.An Thomas Frohwein Aq Mt thfr@openbsd.org
.An Mariusz Zaborski
